### PR TITLE
Enumerable

### PR DESCRIPTION
**Pull request by coker2019**
Added liters.
 - Adding the MyEnumerable module.
 - Adding the all, any, and filter methods.
 - Adding the MyList class and including the MyEnumerable module into it.

### CODE REVIEW

**Review by topeogunleye — APPROVED** [review]
Hi @coker2019, @Graciano1997,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Git flow Not Used ⚠️

- Pull request is to be made from the feature branch into the develop or dev branch not into the main or master branch

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by topeogunleye** [comment]
Note To the Next Reviewer: I was wrong. The GitHub flow used is correct.

image

**Comment by Graciano1997** [comment]
@topeogunleye  thanks

**Comment by coker2019** [comment]
> Hi @coker2019, @Graciano1997,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Git flow Not Used ⚠️
> * Pull request is to be made from the feature branch into the develop or dev branch not into the main or master branch
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag @topeogunleye in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Bantealem — COMMENTED** [review]
# Status: Approved 
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [x] Correct Github flow
- [x] Linters are passed
- [x] Descriptive PR summary
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by coker2019** [comment]
> Note To the Next Reviewer: I was wrong. The GitHub flow used is correct.
> 
> image

Please we are still waiting for a review for this pull request. Can u help out please?

**Comment by topeogunleye** [comment]
> > Note To the Next Reviewer: I was wrong. The GitHub flow used is correct.
> > image
> 
> Please we are still waiting for a review for this pull request. Can u help out please?

It looks like your project has been approved. congratulations 🎊

**Pull request merged**
